test

diff --git a/.github/workflows/rds2json.yml b/.github/workflows/rds2json.yml
--- a/.github/workflows/rds2json.yml
+++ b/.github/workflows/rds2json.yml
@@ -35,10 +35,10 @@ jobs:
         with:
           ref:  ${{ github.head_ref }}    # required for PR
 
-      - name: Early exit (mimics termination)
-        run: |
-          gh run cancel ${{ github.run_id }}
-
+#      - name: Early exit (mimics termination)
+#        run: |
+#          gh run cancel ${{ github.run_id }}
+#
 #          gh run watch ${{ github.run_id }}
 
       - id: files
@@ -47,17 +47,19 @@ jobs:
           filter: |
             '*.rds'
             '*.yml'
-      - run: |
-          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
-          for added_modified_file in "${added_modified_files[@]}"; do
-            echo "Do something with this ${added_modified_file}."
-          done
-          RESULT=0 # failed intermediate result
-          if [ "$RESULT" -eq 0 ]; then
-            echo "intermediate step failed; exit step and entire action"
-            echo "continue=false" >> $GITHUB_OUTPUT
-            exit 1
-          fi
+
+# Below:  necessary??  SEE pilot5, lint ;  write code in R;
+#      - run: |
+#          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
+#          for added_modified_file in "${added_modified_files[@]}"; do
+#            echo "Do something with this ${added_modified_file}."
+#          done
+#          RESULT=0 # failed intermediate result
+#          if [ "$RESULT" -eq 0 ]; then
+#            echo "intermediate step failed; exit step and entire action"
+#            echo "continue=false" >> $GITHUB_OUTPUT
+#            exit 1
+#          fi
 
       - name: Set up R
         uses: r-lib/actions/setup-r@v2
@@ -92,10 +94,13 @@ jobs:
              Therefore I updated the datasetjson (\*.json) files to very latest
              version for submission.
              :heavy_check_mark:
+              (The github.workflow is **${{ github.workflow }}** )
              _(event **${{ github.event_name }}** / attempt **${{ github.run_attempt }}**)_
+
       - name: check outputs
         run: |
           echo "id : ${{ steps.PR_comment.outputs.id }}"
           echo "body : ${{ steps.PR_comment.outputs.body }}"
           echo "html-url : ${{ steps.PR_comment.outputs.html-url }}"
+          
 
